package com.bs.glr.mapper;

import com.bs.glr.bean.DataTable;
import com.bs.glr.bean.DataTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    long countByExample(DataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    int deleteByExample(DataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    int insert(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    int insertSelective(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    List<DataTable> selectByExample(DataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    DataTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    int updateByExampleSelective(@Param("record") DataTable record, @Param("example") DataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    int updateByExample(@Param("record") DataTable record, @Param("example") DataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    int updateByPrimaryKeySelective(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    int updateByPrimaryKey(DataTable record);
}