package com.bs.glr.mapper;

import com.bs.glr.bean.HealthKnowledgeTable;
import com.bs.glr.bean.HealthKnowledgeTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HealthKnowledgeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    long countByExample(HealthKnowledgeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    int deleteByExample(HealthKnowledgeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    int insert(HealthKnowledgeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    int insertSelective(HealthKnowledgeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    List<HealthKnowledgeTable> selectByExample(HealthKnowledgeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    HealthKnowledgeTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    int updateByExampleSelective(@Param("record") HealthKnowledgeTable record, @Param("example") HealthKnowledgeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    int updateByExample(@Param("record") HealthKnowledgeTable record, @Param("example") HealthKnowledgeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    int updateByPrimaryKeySelective(HealthKnowledgeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_knowledge_table
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    int updateByPrimaryKey(HealthKnowledgeTable record);
}