package com.bs.glr.mapper;

import com.bs.glr.bean.MessageTable;
import com.bs.glr.bean.MessageTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    long countByExample(MessageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    int deleteByExample(MessageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    int insert(MessageTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    int insertSelective(MessageTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    List<MessageTable> selectByExample(MessageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    MessageTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    int updateByExampleSelective(@Param("record") MessageTable record, @Param("example") MessageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    int updateByExample(@Param("record") MessageTable record, @Param("example") MessageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    int updateByPrimaryKeySelective(MessageTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_table
     *
     * @mbg.generated Wed Jan 31 22:01:47 CST 2024
     */
    int updateByPrimaryKey(MessageTable record);
}