package com.bs.glr.bean;

public class BsUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.id
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.uname
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.pwd
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.identity
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.parent_name
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.parent_age
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private Integer parentAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.parent_phone_number
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private String parentPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.child_name
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private String childName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.child_age
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private Integer childAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.child_gender
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    private String childGender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.id
     *
     * @return the value of bs_user.id
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.id
     *
     * @param id the value for bs_user.id
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.uname
     *
     * @return the value of bs_user.uname
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.uname
     *
     * @param uname the value for bs_user.uname
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.pwd
     *
     * @return the value of bs_user.pwd
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.pwd
     *
     * @param pwd the value for bs_user.pwd
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.identity
     *
     * @return the value of bs_user.identity
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.identity
     *
     * @param identity the value for bs_user.identity
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.parent_name
     *
     * @return the value of bs_user.parent_name
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.parent_name
     *
     * @param parentName the value for bs_user.parent_name
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.parent_age
     *
     * @return the value of bs_user.parent_age
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public Integer getParentAge() {
        return parentAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.parent_age
     *
     * @param parentAge the value for bs_user.parent_age
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setParentAge(Integer parentAge) {
        this.parentAge = parentAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.parent_phone_number
     *
     * @return the value of bs_user.parent_phone_number
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public String getParentPhoneNumber() {
        return parentPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.parent_phone_number
     *
     * @param parentPhoneNumber the value for bs_user.parent_phone_number
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setParentPhoneNumber(String parentPhoneNumber) {
        this.parentPhoneNumber = parentPhoneNumber == null ? null : parentPhoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.child_name
     *
     * @return the value of bs_user.child_name
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public String getChildName() {
        return childName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.child_name
     *
     * @param childName the value for bs_user.child_name
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setChildName(String childName) {
        this.childName = childName == null ? null : childName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.child_age
     *
     * @return the value of bs_user.child_age
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public Integer getChildAge() {
        return childAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.child_age
     *
     * @param childAge the value for bs_user.child_age
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setChildAge(Integer childAge) {
        this.childAge = childAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.child_gender
     *
     * @return the value of bs_user.child_gender
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public String getChildGender() {
        return childGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.child_gender
     *
     * @param childGender the value for bs_user.child_gender
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setChildGender(String childGender) {
        this.childGender = childGender == null ? null : childGender.trim();
    }
}