package com.bs.glr.bean;

import java.util.ArrayList;
import java.util.List;

public class BsUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public BsUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("uname is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uname is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uname =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uname <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uname >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uname >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uname <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uname <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uname like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uname not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uname in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uname not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uname between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uname not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("pwd is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("pwd is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("pwd =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("pwd <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("pwd >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("pwd >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("pwd <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("pwd <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("pwd like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("pwd not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("pwd in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("pwd not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("pwd between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("pwd not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andIdentityIsNull() {
            addCriterion("identity is null");
            return (Criteria) this;
        }

        public Criteria andIdentityIsNotNull() {
            addCriterion("identity is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityEqualTo(String value) {
            addCriterion("identity =", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotEqualTo(String value) {
            addCriterion("identity <>", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityGreaterThan(String value) {
            addCriterion("identity >", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("identity >=", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLessThan(String value) {
            addCriterion("identity <", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLessThanOrEqualTo(String value) {
            addCriterion("identity <=", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLike(String value) {
            addCriterion("identity like", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotLike(String value) {
            addCriterion("identity not like", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityIn(List<String> values) {
            addCriterion("identity in", values, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotIn(List<String> values) {
            addCriterion("identity not in", values, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityBetween(String value1, String value2) {
            addCriterion("identity between", value1, value2, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotBetween(String value1, String value2) {
            addCriterion("identity not between", value1, value2, "identity");
            return (Criteria) this;
        }

        public Criteria andParentNameIsNull() {
            addCriterion("parent_name is null");
            return (Criteria) this;
        }

        public Criteria andParentNameIsNotNull() {
            addCriterion("parent_name is not null");
            return (Criteria) this;
        }

        public Criteria andParentNameEqualTo(String value) {
            addCriterion("parent_name =", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameNotEqualTo(String value) {
            addCriterion("parent_name <>", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameGreaterThan(String value) {
            addCriterion("parent_name >", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameGreaterThanOrEqualTo(String value) {
            addCriterion("parent_name >=", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameLessThan(String value) {
            addCriterion("parent_name <", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameLessThanOrEqualTo(String value) {
            addCriterion("parent_name <=", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameLike(String value) {
            addCriterion("parent_name like", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameNotLike(String value) {
            addCriterion("parent_name not like", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameIn(List<String> values) {
            addCriterion("parent_name in", values, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameNotIn(List<String> values) {
            addCriterion("parent_name not in", values, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameBetween(String value1, String value2) {
            addCriterion("parent_name between", value1, value2, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameNotBetween(String value1, String value2) {
            addCriterion("parent_name not between", value1, value2, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentAgeIsNull() {
            addCriterion("parent_age is null");
            return (Criteria) this;
        }

        public Criteria andParentAgeIsNotNull() {
            addCriterion("parent_age is not null");
            return (Criteria) this;
        }

        public Criteria andParentAgeEqualTo(Integer value) {
            addCriterion("parent_age =", value, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeNotEqualTo(Integer value) {
            addCriterion("parent_age <>", value, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeGreaterThan(Integer value) {
            addCriterion("parent_age >", value, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_age >=", value, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeLessThan(Integer value) {
            addCriterion("parent_age <", value, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeLessThanOrEqualTo(Integer value) {
            addCriterion("parent_age <=", value, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeIn(List<Integer> values) {
            addCriterion("parent_age in", values, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeNotIn(List<Integer> values) {
            addCriterion("parent_age not in", values, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeBetween(Integer value1, Integer value2) {
            addCriterion("parent_age between", value1, value2, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_age not between", value1, value2, "parentAge");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberIsNull() {
            addCriterion("parent_phone_number is null");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberIsNotNull() {
            addCriterion("parent_phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberEqualTo(String value) {
            addCriterion("parent_phone_number =", value, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberNotEqualTo(String value) {
            addCriterion("parent_phone_number <>", value, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberGreaterThan(String value) {
            addCriterion("parent_phone_number >", value, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("parent_phone_number >=", value, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberLessThan(String value) {
            addCriterion("parent_phone_number <", value, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("parent_phone_number <=", value, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberLike(String value) {
            addCriterion("parent_phone_number like", value, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberNotLike(String value) {
            addCriterion("parent_phone_number not like", value, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberIn(List<String> values) {
            addCriterion("parent_phone_number in", values, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberNotIn(List<String> values) {
            addCriterion("parent_phone_number not in", values, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberBetween(String value1, String value2) {
            addCriterion("parent_phone_number between", value1, value2, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andParentPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("parent_phone_number not between", value1, value2, "parentPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andChildNameIsNull() {
            addCriterion("child_name is null");
            return (Criteria) this;
        }

        public Criteria andChildNameIsNotNull() {
            addCriterion("child_name is not null");
            return (Criteria) this;
        }

        public Criteria andChildNameEqualTo(String value) {
            addCriterion("child_name =", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameNotEqualTo(String value) {
            addCriterion("child_name <>", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameGreaterThan(String value) {
            addCriterion("child_name >", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameGreaterThanOrEqualTo(String value) {
            addCriterion("child_name >=", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameLessThan(String value) {
            addCriterion("child_name <", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameLessThanOrEqualTo(String value) {
            addCriterion("child_name <=", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameLike(String value) {
            addCriterion("child_name like", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameNotLike(String value) {
            addCriterion("child_name not like", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameIn(List<String> values) {
            addCriterion("child_name in", values, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameNotIn(List<String> values) {
            addCriterion("child_name not in", values, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameBetween(String value1, String value2) {
            addCriterion("child_name between", value1, value2, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameNotBetween(String value1, String value2) {
            addCriterion("child_name not between", value1, value2, "childName");
            return (Criteria) this;
        }

        public Criteria andChildAgeIsNull() {
            addCriterion("child_age is null");
            return (Criteria) this;
        }

        public Criteria andChildAgeIsNotNull() {
            addCriterion("child_age is not null");
            return (Criteria) this;
        }

        public Criteria andChildAgeEqualTo(Integer value) {
            addCriterion("child_age =", value, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeNotEqualTo(Integer value) {
            addCriterion("child_age <>", value, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeGreaterThan(Integer value) {
            addCriterion("child_age >", value, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("child_age >=", value, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeLessThan(Integer value) {
            addCriterion("child_age <", value, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeLessThanOrEqualTo(Integer value) {
            addCriterion("child_age <=", value, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeIn(List<Integer> values) {
            addCriterion("child_age in", values, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeNotIn(List<Integer> values) {
            addCriterion("child_age not in", values, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeBetween(Integer value1, Integer value2) {
            addCriterion("child_age between", value1, value2, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("child_age not between", value1, value2, "childAge");
            return (Criteria) this;
        }

        public Criteria andChildGenderIsNull() {
            addCriterion("child_gender is null");
            return (Criteria) this;
        }

        public Criteria andChildGenderIsNotNull() {
            addCriterion("child_gender is not null");
            return (Criteria) this;
        }

        public Criteria andChildGenderEqualTo(String value) {
            addCriterion("child_gender =", value, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderNotEqualTo(String value) {
            addCriterion("child_gender <>", value, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderGreaterThan(String value) {
            addCriterion("child_gender >", value, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderGreaterThanOrEqualTo(String value) {
            addCriterion("child_gender >=", value, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderLessThan(String value) {
            addCriterion("child_gender <", value, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderLessThanOrEqualTo(String value) {
            addCriterion("child_gender <=", value, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderLike(String value) {
            addCriterion("child_gender like", value, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderNotLike(String value) {
            addCriterion("child_gender not like", value, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderIn(List<String> values) {
            addCriterion("child_gender in", values, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderNotIn(List<String> values) {
            addCriterion("child_gender not in", values, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderBetween(String value1, String value2) {
            addCriterion("child_gender between", value1, value2, "childGender");
            return (Criteria) this;
        }

        public Criteria andChildGenderNotBetween(String value1, String value2) {
            addCriterion("child_gender not between", value1, value2, "childGender");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_user
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 31 20:59:07 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_user
     *
     * @mbg.generated Wed Jan 31 20:59:07 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}