package com.bs.glr.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DataTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public DataTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("uname is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uname is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uname =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uname <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uname >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uname >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uname <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uname <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uname like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uname not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uname in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uname not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uname between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uname not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andChildNameIsNull() {
            addCriterion("child_name is null");
            return (Criteria) this;
        }

        public Criteria andChildNameIsNotNull() {
            addCriterion("child_name is not null");
            return (Criteria) this;
        }

        public Criteria andChildNameEqualTo(String value) {
            addCriterion("child_name =", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameNotEqualTo(String value) {
            addCriterion("child_name <>", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameGreaterThan(String value) {
            addCriterion("child_name >", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameGreaterThanOrEqualTo(String value) {
            addCriterion("child_name >=", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameLessThan(String value) {
            addCriterion("child_name <", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameLessThanOrEqualTo(String value) {
            addCriterion("child_name <=", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameLike(String value) {
            addCriterion("child_name like", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameNotLike(String value) {
            addCriterion("child_name not like", value, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameIn(List<String> values) {
            addCriterion("child_name in", values, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameNotIn(List<String> values) {
            addCriterion("child_name not in", values, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameBetween(String value1, String value2) {
            addCriterion("child_name between", value1, value2, "childName");
            return (Criteria) this;
        }

        public Criteria andChildNameNotBetween(String value1, String value2) {
            addCriterion("child_name not between", value1, value2, "childName");
            return (Criteria) this;
        }

        public Criteria andHeartRateIsNull() {
            addCriterion("heart_rate is null");
            return (Criteria) this;
        }

        public Criteria andHeartRateIsNotNull() {
            addCriterion("heart_rate is not null");
            return (Criteria) this;
        }

        public Criteria andHeartRateEqualTo(String value) {
            addCriterion("heart_rate =", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotEqualTo(String value) {
            addCriterion("heart_rate <>", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateGreaterThan(String value) {
            addCriterion("heart_rate >", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateGreaterThanOrEqualTo(String value) {
            addCriterion("heart_rate >=", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLessThan(String value) {
            addCriterion("heart_rate <", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLessThanOrEqualTo(String value) {
            addCriterion("heart_rate <=", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLike(String value) {
            addCriterion("heart_rate like", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotLike(String value) {
            addCriterion("heart_rate not like", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateIn(List<String> values) {
            addCriterion("heart_rate in", values, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotIn(List<String> values) {
            addCriterion("heart_rate not in", values, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateBetween(String value1, String value2) {
            addCriterion("heart_rate between", value1, value2, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotBetween(String value1, String value2) {
            addCriterion("heart_rate not between", value1, value2, "heartRate");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenIsNull() {
            addCriterion("blood_oxygen is null");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenIsNotNull() {
            addCriterion("blood_oxygen is not null");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenEqualTo(String value) {
            addCriterion("blood_oxygen =", value, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenNotEqualTo(String value) {
            addCriterion("blood_oxygen <>", value, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenGreaterThan(String value) {
            addCriterion("blood_oxygen >", value, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenGreaterThanOrEqualTo(String value) {
            addCriterion("blood_oxygen >=", value, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenLessThan(String value) {
            addCriterion("blood_oxygen <", value, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenLessThanOrEqualTo(String value) {
            addCriterion("blood_oxygen <=", value, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenLike(String value) {
            addCriterion("blood_oxygen like", value, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenNotLike(String value) {
            addCriterion("blood_oxygen not like", value, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenIn(List<String> values) {
            addCriterion("blood_oxygen in", values, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenNotIn(List<String> values) {
            addCriterion("blood_oxygen not in", values, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenBetween(String value1, String value2) {
            addCriterion("blood_oxygen between", value1, value2, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBloodOxygenNotBetween(String value1, String value2) {
            addCriterion("blood_oxygen not between", value1, value2, "bloodOxygen");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureIsNull() {
            addCriterion("body_temperature is null");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureIsNotNull() {
            addCriterion("body_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureEqualTo(String value) {
            addCriterion("body_temperature =", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureNotEqualTo(String value) {
            addCriterion("body_temperature <>", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureGreaterThan(String value) {
            addCriterion("body_temperature >", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("body_temperature >=", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureLessThan(String value) {
            addCriterion("body_temperature <", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureLessThanOrEqualTo(String value) {
            addCriterion("body_temperature <=", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureLike(String value) {
            addCriterion("body_temperature like", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureNotLike(String value) {
            addCriterion("body_temperature not like", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureIn(List<String> values) {
            addCriterion("body_temperature in", values, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureNotIn(List<String> values) {
            addCriterion("body_temperature not in", values, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureBetween(String value1, String value2) {
            addCriterion("body_temperature between", value1, value2, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureNotBetween(String value1, String value2) {
            addCriterion("body_temperature not between", value1, value2, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_table
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 31 21:29:38 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_table
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}