package com.bs.glr.bean;

import java.util.Date;

public class DataTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.id
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.uname
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.child_name
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    private String childName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.heart_rate
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    private String heartRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.blood_oxygen
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    private String bloodOxygen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.body_temperature
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    private String bodyTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.ctime
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.id
     *
     * @return the value of data_table.id
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.id
     *
     * @param id the value for data_table.id
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.uname
     *
     * @return the value of data_table.uname
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.uname
     *
     * @param uname the value for data_table.uname
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.child_name
     *
     * @return the value of data_table.child_name
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public String getChildName() {
        return childName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.child_name
     *
     * @param childName the value for data_table.child_name
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setChildName(String childName) {
        this.childName = childName == null ? null : childName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.heart_rate
     *
     * @return the value of data_table.heart_rate
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public String getHeartRate() {
        return heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.heart_rate
     *
     * @param heartRate the value for data_table.heart_rate
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setHeartRate(String heartRate) {
        this.heartRate = heartRate == null ? null : heartRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.blood_oxygen
     *
     * @return the value of data_table.blood_oxygen
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public String getBloodOxygen() {
        return bloodOxygen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.blood_oxygen
     *
     * @param bloodOxygen the value for data_table.blood_oxygen
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setBloodOxygen(String bloodOxygen) {
        this.bloodOxygen = bloodOxygen == null ? null : bloodOxygen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.body_temperature
     *
     * @return the value of data_table.body_temperature
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public String getBodyTemperature() {
        return bodyTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.body_temperature
     *
     * @param bodyTemperature the value for data_table.body_temperature
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setBodyTemperature(String bodyTemperature) {
        this.bodyTemperature = bodyTemperature == null ? null : bodyTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.ctime
     *
     * @return the value of data_table.ctime
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.ctime
     *
     * @param ctime the value for data_table.ctime
     *
     * @mbg.generated Wed Jan 31 21:29:38 CST 2024
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}