package com.bs.glr.bean;

import java.util.Date;

public class HealthKnowledgeTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_knowledge_table.id
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_knowledge_table.publisher
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_knowledge_table.category
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_knowledge_table.content
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_knowledge_table.publish_time
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    private Date publishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_knowledge_table.id
     *
     * @return the value of health_knowledge_table.id
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_knowledge_table.id
     *
     * @param id the value for health_knowledge_table.id
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_knowledge_table.publisher
     *
     * @return the value of health_knowledge_table.publisher
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_knowledge_table.publisher
     *
     * @param publisher the value for health_knowledge_table.publisher
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_knowledge_table.category
     *
     * @return the value of health_knowledge_table.category
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_knowledge_table.category
     *
     * @param category the value for health_knowledge_table.category
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_knowledge_table.content
     *
     * @return the value of health_knowledge_table.content
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_knowledge_table.content
     *
     * @param content the value for health_knowledge_table.content
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_knowledge_table.publish_time
     *
     * @return the value of health_knowledge_table.publish_time
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_knowledge_table.publish_time
     *
     * @param publishTime the value for health_knowledge_table.publish_time
     *
     * @mbg.generated Wed Jan 31 22:29:50 CST 2024
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }
}