package com.bs.glr.bean;

public class MessageTableWithBLOBs extends MessageTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_table.message_content
     *
     * @mbg.generated Wed Jan 31 21:59:50 CST 2024
     */
    private String messageContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_table.message_reply
     *
     * @mbg.generated Wed Jan 31 21:59:50 CST 2024
     */
    private String messageReply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_table.message_content
     *
     * @return the value of message_table.message_content
     *
     * @mbg.generated Wed Jan 31 21:59:50 CST 2024
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_table.message_content
     *
     * @param messageContent the value for message_table.message_content
     *
     * @mbg.generated Wed Jan 31 21:59:50 CST 2024
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_table.message_reply
     *
     * @return the value of message_table.message_reply
     *
     * @mbg.generated Wed Jan 31 21:59:50 CST 2024
     */
    public String getMessageReply() {
        return messageReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_table.message_reply
     *
     * @param messageReply the value for message_table.message_reply
     *
     * @mbg.generated Wed Jan 31 21:59:50 CST 2024
     */
    public void setMessageReply(String messageReply) {
        this.messageReply = messageReply == null ? null : messageReply.trim();
    }
}